"""
YOLO Data Preparation -- EcoStream AI Autoresearch
STATIC FILE: The autoresearch agent must NEVER modify this file.

Orchestrates the full data pipeline:
  1. Download TACO annotations from GitHub
  2. Download images from Flickr (--subset N for speed)
  3. Convert COCO -> YOLO segmentation format (60 TACO cats -> 20 EcoStream classes)
  4. Write data/processed/dataset.yaml with absolute paths
  5. Verify all splits have images

Usage:
    python ml-models/yolo/prepare.py                # default: 600 images
    python ml-models/yolo/prepare.py --subset 200   # faster for experiments
    python ml-models/yolo/prepare.py --subset 50    # tiny for smoke tests
"""

import argparse
import sys
from pathlib import Path

# Resolve paths relative to project root (two levels up from this file)
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

# Add ml-models/yolo to sys.path so we can import sibling modules
_yolo_dir = str(PROJECT_ROOT / "ml-models" / "yolo")
if _yolo_dir not in sys.path:
    sys.path.insert(0, _yolo_dir)

# 20 EcoStream class names -- must match dataset.yaml and inference.py
CLASS_NAMES = [
    "plastic_pet_bottle", "plastic_bag", "plastic_wrapper",
    "glass_bottle", "glass_broken", "paper_newspaper",
    "paper_cardboard", "metal_can", "metal_scrap",
    "organic_food_waste", "organic_leaves", "e_waste_phone",
    "e_waste_battery", "textile_cloth", "rubber_tire",
    "construction_debris", "medical_waste_mask", "thermocol",
    "tetra_pak", "mixed_waste",
]


def write_dataset_yaml(processed_dir: Path):
    """Write dataset.yaml with absolute paths so ultralytics resolves regardless of CWD."""
    yaml_path = processed_dir / "dataset.yaml"
    abs_path = str(processed_dir).replace("\\", "/")
    names_block = "\n".join(f"  {i}: {name}" for i, name in enumerate(CLASS_NAMES))
    content = f"""# Auto-generated by prepare.py -- DO NOT EDIT
# Absolute paths for ultralytics compatibility
path: {abs_path}
train: train/images
val: val/images
test: test/images

nc: {len(CLASS_NAMES)}
names:
{names_block}
"""
    yaml_path.write_text(content)
    print(f"[OK] dataset.yaml written -> {yaml_path}")


def verify_splits(processed_dir: Path) -> bool:
    """Verify all splits have images. Returns True if OK."""
    ok = True
    for split in ("train", "val", "test"):
        img_dir = processed_dir / split / "images"
        lbl_dir = processed_dir / split / "labels"
        n_imgs = len(list(img_dir.glob("*"))) if img_dir.exists() else 0
        n_lbls = len(list(lbl_dir.glob("*.txt"))) if lbl_dir.exists() else 0
        status = "OK" if n_imgs > 0 else "EMPTY"
        print(f"  [{status}] {split:<5}: {n_imgs} images, {n_lbls} labels")
        if n_imgs == 0:
            ok = False
    return ok


def print_class_distribution(processed_dir: Path):
    """Parse all train label files and print per-class instance counts.

    This exposes the class imbalance the autoresearch agent must work around.
    Classes with 0 instances (organic_leaves, e_waste_phone, rubber_tire,
    construction_debris) have no TACO source data -- the agent cannot fix this
    with hyperparameter tuning alone.
    """
    from collections import Counter
    counts = Counter()
    lbl_dir = processed_dir / "train" / "labels"
    if not lbl_dir.exists():
        return
    for lbl_file in lbl_dir.glob("*.txt"):
        for line in lbl_file.read_text().strip().split("\n"):
            if line.strip():
                cls_id = int(line.split()[0])
                counts[cls_id] += 1

    total = sum(counts.values())
    print(f"\n  Class distribution in train split ({total} instances):")
    print(f"  {'ID':>3}  {'Class':<25} {'Count':>6}  {'Pct':>5}  Status")
    print(f"  {'---':>3}  {'-'*25:<25} {'-----':>6}  {'-----':>5}  ------")
    for i, name in enumerate(CLASS_NAMES):
        c = counts.get(i, 0)
        pct = (c / total * 100) if total > 0 else 0
        if c == 0:
            flag = "!! ZERO -- no TACO source"
        elif pct < 1.0:
            flag = "! rare"
        else:
            flag = ""
        print(f"  {i:3d}  {name:<25} {c:6d}  {pct:4.1f}%  {flag}")


def main():
    parser = argparse.ArgumentParser(description="Prepare TACO dataset for YOLO training")
    parser.add_argument("--subset", type=int, default=600,
                        help="Download first N images (default: 600)")
    parser.add_argument("--skip-download", action="store_true",
                        help="Skip download step (use existing raw images)")
    args = parser.parse_args()

    print("=" * 60)
    print("  EcoStream AI -- YOLO Data Preparation")
    print("=" * 60)

    # Step 1+2: Download annotations and images
    if not args.skip_download:
        from download_dataset import download_annotations, download_images

        print("\n[Step 1/4] Downloading TACO annotations...")
        data = download_annotations(DATA_RAW)

        print(f"\n[Step 2/4] Downloading images (subset={args.subset})...")
        download_images(data, DATA_RAW / "images", subset=args.subset)
    else:
        print("\n[Step 1-2/4] Skipped download (--skip-download)")

    # Step 3: Convert COCO -> YOLO
    ann_file = DATA_RAW / "annotations" / "instances.json"
    if not ann_file.exists():
        print(f"[ERROR] Annotations not found: {ann_file}")
        print("  Run without --skip-download first.")
        sys.exit(1)

    print("\n[Step 3/4] Converting COCO -> YOLO segmentation format...")
    from data_prep import coco_to_yolo_seg
    coco_to_yolo_seg(
        coco_json=str(ann_file),
        images_dir=str(DATA_RAW / "images"),
        output_dir=str(DATA_PROCESSED),
    )

    # Step 4: Write dataset.yaml with absolute paths
    print("\n[Step 4/4] Writing dataset.yaml with absolute paths...")
    write_dataset_yaml(DATA_PROCESSED)

    # Verify
    print("\nVerifying splits:")
    if not verify_splits(DATA_PROCESSED):
        print("\n[ERROR] Some splits are empty. Check the download and conversion steps.")
        sys.exit(1)

    # Class imbalance report -- critical context for the autoresearch agent
    print_class_distribution(DATA_PROCESSED)

    print("\n" + "=" * 60)
    print("  Data preparation complete!")
    print(f"  Dataset YAML: {DATA_PROCESSED / 'dataset.yaml'}")
    print("  Next: python ml-models/yolo/train.py")
    print("=" * 60)


if __name__ == "__main__":
    main()
