"""
vision/train.py  --  EcoStream AI YOLO Training Script
=======================================================
Trains TWO models on the 20-class Indian waste dataset:
  1. YOLOv11s-seg  (production)  -> vision/model/best.pt
  2. YOLOv8n       (bbox baseline for ablation study) -> vision/model/baseline.pt

Dataset expected at  dataset/augmented/dataset.yaml
(generated by dataset/gan_mix.py)

Usage:
    python vision/train.py

Week 10: run tests/test_yolo.py to compare both models and get paper KPIs.

Owned by: M1a Prajwal Patil (AI/Vision Lead)
"""

import shutil
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Experiment knobs (edit these)
# ---------------------------------------------------------------------------
MODEL_VARIANT  = "yolo11s-seg.pt"  # 9.4M params -- production segmentation model
BASELINE_MODEL = "yolov8n.pt"      # YOLOv8 nano bbox -- ablation baseline only
IMGSZ          = 416
BATCH_SIZE     = 8
EPOCHS         = 100               # minimum 100 per Member 1 guide
OPTIMIZER      = "AdamW"
LR0            = 0.001
PATIENCE       = 30                # early-stop patience
FREEZE_LAYERS  = 10                # freeze first N layers (transfer learning)

# ---------------------------------------------------------------------------
# Fixed constants
# ---------------------------------------------------------------------------
WALL_CLOCK_BUDGET_SEC = 36000  # 10 h hard stop (callback-based, Windows-safe)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_YAML = PROJECT_ROOT / "dataset" / "augmented" / "dataset.yaml"
MODEL_DIR    = PROJECT_ROOT / "vision" / "model"   # best.pt + baseline.pt go here
NC           = 20              # 20 Indian waste classes -- LOCKED


def main():
    if not DATASET_YAML.exists():
        print(f"[ERROR] {DATASET_YAML} not found.")
        print("  Run dataset preparation first:  python dataset/gan_mix.py")
        sys.exit(1)

    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("  EcoStream AI -- YOLO Training")
    print("=" * 60)
    print(f"  Model    : {MODEL_VARIANT}")
    print(f"  ImgSz    : {IMGSZ}")
    print(f"  Batch    : {BATCH_SIZE}")
    print(f"  Epochs   : {EPOCHS}")
    print(f"  Dataset  : {DATASET_YAML}")
    print(f"  Budget   : {WALL_CLOCK_BUDGET_SEC}s ({WALL_CLOCK_BUDGET_SEC/3600:.1f}h)")
    print("=" * 60)

    from ultralytics import YOLO

    model = YOLO(MODEL_VARIANT)

    # -- Wall-clock budget guard (callback) ----------------------------------
    _start = time.monotonic()
    _epoch_times = []

    def _time_guard(trainer):
        now = time.monotonic()
        _epoch_times.append(now)
        elapsed = now - _start
        last_dur = (_epoch_times[-1] - _epoch_times[-2]) if len(_epoch_times) >= 2 else elapsed
        if (WALL_CLOCK_BUDGET_SEC - elapsed) < last_dur * 1.3:
            epoch = getattr(trainer, "epoch", "?")
            print(f"\n[BUDGET] Stopping at epoch {epoch} -- "
                  f"{elapsed:.0f}s elapsed, ~{last_dur:.0f}s/epoch remaining")
            trainer.stop = True

    model.add_callback("on_train_epoch_end", _time_guard)

    # -- Train ---------------------------------------------------------------
    results = model.train(
        data=str(DATASET_YAML),
        epochs=EPOCHS,
        patience=PATIENCE,
        imgsz=IMGSZ,
        batch=BATCH_SIZE,
        device="cpu",
        workers=0,
        optimizer=OPTIMIZER,
        lr0=LR0,
        lrf=0.01,
        momentum=0.937,
        weight_decay=0.0005,
        warmup_epochs=3.0,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        fliplr=0.5,
        mosaic=1.0,
        mixup=0.1,
        copy_paste=0.5,
        close_mosaic=10,
        conf=0.25,
        iou=0.45,
        freeze=FREEZE_LAYERS,
        project=str(PROJECT_ROOT / "runs" / "segment"),
        name="autoresearch",
        exist_ok=True,
        plots=True,
        cache=True,
    )

    # -- Copy best weights to vision/model/ ----------------------------------
    best_src = Path(results.save_dir) / "weights" / "best.pt"
    if best_src.exists():
        shutil.copy(best_src, MODEL_DIR / "best.pt")
        print(f"\n[OK] Saved production weights -> {MODEL_DIR / 'best.pt'}")

    # -- Capture YOLOv11 metrics for comparison table ------------------------
    seg_map50 = seg_map5095 = seg_prec = seg_rec = 0.0
    try:
        m = results.results_dict
        seg_map50   = m.get("metrics/mAP50(M)",    0)
        seg_map5095 = m.get("metrics/mAP50-95(M)", 0)
        seg_prec    = m.get("metrics/precision(M)", 0)
        seg_rec     = m.get("metrics/recall(M)",    0)
    except Exception:
        pass

    # -----------------------------------------------------------------------
    # Phase 2 -- YOLOv8n bounding-box baseline (ablation study, Week 10)
    # -----------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("  Phase 2: YOLOv8n bbox baseline")
    print("=" * 60)

    baseline = YOLO(BASELINE_MODEL)
    results_baseline = baseline.train(
        data=str(DATASET_YAML),
        epochs=EPOCHS,
        patience=PATIENCE,
        imgsz=IMGSZ,
        batch=BATCH_SIZE,
        device="cpu",
        workers=0,
        optimizer=OPTIMIZER,
        lr0=LR0,
        lrf=0.01,
        momentum=0.937,
        weight_decay=0.0005,
        warmup_epochs=3.0,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        fliplr=0.5,
        mosaic=1.0,
        close_mosaic=10,
        project=str(PROJECT_ROOT / "runs" / "detect"),
        name="baseline",
        exist_ok=True,
        plots=True,
        cache=True,
    )

    baseline_best = Path(results_baseline.save_dir) / "weights" / "best.pt"
    if baseline_best.exists():
        shutil.copy(baseline_best, MODEL_DIR / "baseline.pt")
        print(f"\n[OK] Saved baseline weights -> {MODEL_DIR / 'baseline.pt'}")

    box_map50 = box_map5095 = box_prec = box_rec = 0.0
    try:
        mb = results_baseline.results_dict
        box_map50   = mb.get("metrics/mAP50(B)",    0)
        box_map5095 = mb.get("metrics/mAP50-95(B)", 0)
        box_prec    = mb.get("metrics/precision(B)", 0)
        box_rec     = mb.get("metrics/recall(B)",    0)
    except Exception:
        pass

    # -- Side-by-side comparison table ---------------------------------------
    print("\n" + "=" * 60)
    print("  ABLATION STUDY — FINAL METRICS")
    print("=" * 60)
    print(f"  {'Metric':<20} {'YOLOv8n bbox':>14} {'YOLOv11s-seg':>14}")
    print(f"  {'-'*20} {'-'*14} {'-'*14}")
    print(f"  {'mAP50':<20} {box_map50:>14.4f} {seg_map50:>14.4f}")
    print(f"  {'mAP50-95':<20} {box_map5095:>14.4f} {seg_map5095:>14.4f}")
    print(f"  {'Precision':<20} {box_prec:>14.4f} {seg_prec:>14.4f}")
    print(f"  {'Recall':<20} {box_rec:>14.4f} {seg_rec:>14.4f}")
    if box_map50 > 0:
        improvement = (seg_map50 - box_map50) / box_map50 * 100
        print(f"  {'mAP50 improvement':<20} {improvement:>+13.1f}%")
    print("=" * 60)
    print("\n  Weights saved:")
    print(f"    Production : {MODEL_DIR / 'best.pt'}")
    print(f"    Baseline   : {MODEL_DIR / 'baseline.pt'}")
    print("=" * 60)


if __name__ == "__main__":
    main()
